### ISSUE TITLE
Hiding previous card

### ISSUE THREAD

**Issue by VisvaldasG** [JoniVR/VerticalCardSwiper#26] opened 2018-12-03 23:34 UTC
Is there a way to hide a previous card after scrolling up. I have tried to implement `isPreviousCardVisible: Bool = false` both in code and in IB, but previous card is always visible

Thanks!

**Comment by JoniVR** [comment] 2018-12-04 07:41
Hi @VisvaldasG 

What exactly do you mean with hiding the previous card? 

Because for me this is working as intended.
I added the following inside `viewDidLoad()` in the example:
```swift
cardSwiper.isPreviousCardVisible = false
```
The variable `isPreviousCardVisible` is meant to hide the card below the focussed card as you can see below:
### `isPreviousCardVisible = true`
<img src="https://user-images.githubusercontent.com/7591717/49425984-5f910380-f79f-11e8-9251-5e236bcd5cc6.png" alt="isPreviousCardVisbleTrue" width= 200px/>

### `isPreviousCardVisible = false`
<img src="https://user-images.githubusercontent.com/7591717/49426066-abdc4380-f79f-11e8-944d-ece749b60d8b.png" alt="isPreviousCardVisbleFalse" width= 200px/>

Best regards,
Joni

**Comment by VisvaldasG** [comment] 2018-12-04 14:43
Hi Joni,
sorry it was a mistake, it was a mismatch in settings in IB and in ViewController class…
This problem is solved, thanks for your quick response.

But I have another question. Is the way to make all rejected cards from the bottom to scroll behind not to the front?
Im trying to create some flashcard app and it doesn't make any sense te see the same card behind during the studying when the rejected from the bottom scrolls over… I'd like to have it in front and to swipe left or right or back to the bottom depending if the answer is correct or not…

Anyway,
Thanks for the help
Visvaldas

**Comment by JoniVR** [comment] 2018-12-04 19:27
Could you clarify this a bit? 
I don't think I entirely understand what you mean. Perhaps some pictures or a video or something?

**Comment by VisvaldasG** [comment] 2018-12-04 20:19
OK. I'll try with the video.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15321354/49469837-d31b2b00-f808-11e8-8804-88ff34a76665.gif)

For example. Jon Doe card is always visible. All cards Pamela, Ed, Nicki, Barac and others scrolls on the top of Jon Doe, and it's not accesible until the rest of the cards will finish scroll on the top. Its quite boring to see Joe's card all study time... Probably the data array should be rearranged somehow. After left or right swipe cards are deleted from data array with . How can I access Joe's  card send it to the end of data array
Thanks
Visvaldas  
 

PS The only possible way to access Joe's card is to scroll down upper card and then to swipe it away, but probably it's not very user friendly

**Comment by JoniVR** [comment] 2018-12-05 10:48
So if I understand correctly, you want to show no cards behind the focussed card? So when you swipe away a card, only the background is visible? 

If that's the case, you could just try disabling scrolling on the `VerticalCardSwiperView`, that way the user won't be able to scroll down and you'll just only see the top card. I don't know if that satisfies your requirements, but that would be the easiest way to achieve that.

**Comment by VisvaldasG** [comment] 2018-12-05 12:26
Would be one of the options. Or cards from the bottom scroll up behind the focussed card.

**Comment by JoniVR** [comment] 2018-12-07 18:39
Yeah, if that's what you want to achieve then you probably need to play around with the `updateCellAttributes` function inside the `VerticalCardSwiperFlowLayout.swift` file. On the development branch I recently added a lot of documentation to that function on how exactly it works. 

You'll have to look into doing this yourself as this is not something I plan on implementing and it doesn't really impact the library. 

Hope that helps. I'm going to be closing this issue for now, feel free to reopen if you have further questions.

**Closed as completed by JoniVR** 2018-12-07 18:39 UTC
Labels: question
