### ISSUE TITLE
Strange behaviour of CardCell layout

### ISSUE THREAD

**Issue by Lavmint** [JoniVR/VerticalCardSwiper#29] opened 2018-12-25 21:39 UTC
### New Issue Checklist

- [x] I updated VerticalCardSwiper to the latest version.
- [x] I read the [Contribution Guidelines](CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/JoniVR/VerticalCardSwiper).
- [x] I searched for [existing GitHub issues](https://github.com/JoniVR/VerticalCardSwiper/issues).

### Issue Description

Steps to reproduce:
1. Create `UIViewController` and add `UILabel` inside of it, stretch label to edges with constraints
2. Add VC's `view` as subview to `CardView`, stretch VC's `view` to edges of `CardView` with constraints
3. Run app and try to scroll, it seems that glitch depends on size of text

![output](https://user-images.githubusercontent.com/8833633/50426667-6a761a00-08ad-11e9-884c-72db52b52182.gif)

### Environment
- **iOS Version**: iOS 12.1
- **Device(s)**: iPhone 5S Simulator
- **Xcode Version**: 10.1 (10B61)

**Comment by JoniVR** [comment] 2018-12-25 21:54
Hi @Lavmint

This is (most probably) due to the `firstItemTransform` property of the custom flowlayout. 

Because the card resizes (transforms) once it gets pushed to the background, the contents of the card need to be resized too (this happens at every bounds change, see the `shouldInvalidateLayout` function inside `VerticalCardSwiperFlowLayout.swift`). 

So everything is actually working as intended (including the constraints). 

Possible solutions:
* The first obvious solution would be to set the `firstItemTransform` property of the `VerticalCardSwiper` to 0. Although you would lose the effect by doing that.
* You can also try playing around with the constraints, setting <= or >= value on leading and trailing edges and giving a width to the `UILabel` or something along those lines. 
You might also want to look into *[content hugging and compression resistance priorities](https://medium.com/@abhimuralidharan/ios-content-hugging-and-content-compression-resistance-priorities-476fb5828ef)*.

Hope this helps. 😄 

I'll be closing this for now as it's intended behaviour. 
Feel free to reopen if you have feedback, questions or remarks. 🙂

Best regards
Joni

**Closed as completed by JoniVR** 2018-12-25 21:54 UTC
Labels: discussion
